---

# ------------------------------------------------------------------------------
# Solaris - grab package version 
# ------------------------------------------------------------------------------

# Grab installed version of package 
- name: get {{ package_key }} version
  command:
    cmd: pkginfo -l {{ package_name }}
  register: pkg_version
  changed_when: false
  failed_when: false
  ignore_errors: true
