---

# Set failed
- set_fact:
    cacheable: true
    sas_sudoers:
      unreachable: false
      failed: true
      changed: "{{ result.changed | default(False) }}"
      msg: |
        sudoers:
        {{ result.msg | default('Unexpected error') }}
    sas_common:
      unreachable: false
      failed: true
      changed: "{{ result.changed | default(False) }}"
      msg: |
        sudoers:
        {{ result.msg | default('Unexpected error') }}
  when: sudoers_reports_generate or sudoers_facts_generate

# Propogate fail
- fail:
    msg: "{{ result.msg | default('Unexpected error') }}"
