---

# ------------------------------------------------------------------------------
# Darwin - remove package 
# ------------------------------------------------------------------------------

# TODO: This needs to be fixed for use with PM

# Run installer
- name: remove {{ package_key }}
  command: /opt/quest/libexec/vas/macos/Uninstall.app/Contents/MacOS/Uninstall --console --force {{ package_name }}
  register: pkg_remove 
  ignore_errors: true
  failed_when: pkg_remove.stdout | lower is search("failed")
