---

# Grab group
- fetch:
    src: '/etc/group'
    #dest: "{{ sudoers_tmp_dir }}/{{ inventory_hostname }}_group"
    #flat: true
    dest: "{{ sudoers_tmp_dir }}"
  register: result

# Fail if there was a message returned
- fail:
    msg: "{{ result.msg }}"
  when: result.msg is defined and result.msg
