---

# Capture requested state
- include_tasks: utils/set_state.yml
  vars:
    flag: req 
    value: "{{ state }}" 
  when: software_reports_generate or software_facts_generate

# Check if OS not supported
# NOTE: This causes the host to fail so it won't show up the report  
- name: OS {{ ansible_facts['os_family'] }} is not supported
  block:

    - include_tasks: utils/set_state.yml
      vars:
        flag: act 
        value: failed
      when: software_reports_generate or software_facts_generate

    - fail:
        msg: OS {{ ansible_facts['os_family'] }} is not supported

  when: 
    - ansible_facts['os_family'] | lower not in software_os_families

# Handle remove 
- name: remove {{ package_key }} 
  block:

    - include_tasks: os/{{ ansible_facts['os_family'] | lower }}/remove.yml

    - include_tasks: utils/set_state.yml
      vars:
        flag: act 
        value: removed
      when: software_reports_generate or software_facts_generate

  rescue:

    - include_tasks: utils/set_state.yml
      vars:
        flag: act 
        value: failed
      when: software_reports_generate or software_facts_generate

    - fail:
        msg: failed to remove {{ package_key }} package

  when:
    - state == 'absent'
    - hostvars[inventory_hostname]['sas_software_' + package_key + '_vers_beg']

# Handle install
- name: install {{ package_key }} 
  block:

    - include_tasks: os/{{ ansible_facts['os_family'] | lower }}/install.yml

    - include_tasks: utils/set_state.yml
      vars:
        flag: act 
        value: installed 
      when: software_reports_generate or software_facts_generate

  rescue:

    - include_tasks: utils/set_state.yml
      vars:
        flag: act 
        value: failed
      when: software_reports_generate or software_facts_generate
        
    - fail:
        msg: failed to install {{ package_key }} package

  when: 
    - package_key in software_pkgs['packages']
    - state == 'present'
    - not hostvars[inventory_hostname]['sas_software_' + package_key + '_vers_beg']

# Handle upgrade
- name: upgrade {{ package_key }}
  block:

    - include_tasks: os/{{ ansible_facts['os_family'] | lower }}/upgrade.yml

    - include_tasks: utils/set_state.yml
      vars:
        flag: act 
        value: upgraded
      when: software_reports_generate or software_facts_generate

  rescue:

    - include_tasks: utils/set_state.yml
      vars:
        flag: act 
        value: failed
      when: software_reports_generate or software_facts_generate

    - fail:
        msg: failed to upgrade {{ package_key }} package

  when: 
    - package_key in software_pkgs['packages']
    - state == 'present'
    - hostvars[inventory_hostname]['sas_software_' + package_key + '_vers_beg'] 
    - hostvars[inventory_hostname]['sas_software_' + package_key + '_vers_beg'] < software_pkgs['packages'][package_key]['vers']

# Handle downgrade
- name: downgrade {{ package_key }}
  block:

    - include_tasks: os/{{ ansible_facts['os_family'] | lower }}/downgrade.yml

    - include_tasks: utils/set_state.yml
      vars:
        flag: act 
        value: downgraded
      when: software_reports_generate or software_facts_generate

  rescue:

    - include_tasks: utils/set_state.yml
      vars:
        flag: act 
        value: failed
      when: software_reports_generate or software_facts_generate

    - fail:
        msg: failed to downgrade {{ package_key }} package

  when: 
    - package_key in software_pkgs['packages']
    - state == 'present'
    - hostvars[inventory_hostname]['sas_software_' + package_key + '_vers_beg'] 
    - hostvars[inventory_hostname]['sas_software_' + package_key + '_vers_beg'] > software_pkgs['packages'][package_key]['vers']

# Handle no action 
- include_tasks: utils/set_state.yml
  vars:
    flag: act 
    value: none 
  when:
    - software_reports_generate or software_facts_generate
    - not (hostvars[inventory_hostname]['sas_software_' + package_key + '_act'] | default('')) 
