---

# Delete temporary directory on host
- name: delete temp directory {{ package_dest_dir }} 
  file: 
    path: "{{ package_dest_dir }}"
    state: absent
  ignore_errors: true
  changed_when: false
  register: result

- fail:
    msg: "{{ result.msg }}"
  when: result.failed
