---

# Set success
- set_fact:
    cacheable: true
    sas_sudo_policy_for_unix_host:
      unreachable: false
      failed: false
      changed: false
  when: sudo_policy_for_unix_host_reports_generate or sudo_policy_for_unix_host_facts_generate
