---

# Preflight settings
# ------------------------------------------------------------------------------

# Preflight mode
# Valid options are: 'sudo', 'pmpolicy', 'server'
preflight_mode: 'sudo'
preflight_verbose: false
preflight_extra_args: ''


# Facts settings
# ------------------------------------------------------------------------------

preflight_facts_generate: "{{ facts_generate }}"
preflight_facts_verbose: "{{ facts_verbose }}"


# Reports settings
# ------------------------------------------------------------------------------

preflight_reports_generate: "{{ reports_generate }}"
preflight_reports_backup: "{{ reports_backup }}"

# Format of details section in both HTML and CSV reports
# Valid options are: 'yaml' or 'json'
preflight_reports_details_format: "{{ reports_details_format }}"

# On which host should the reports be generated.
# TODO: This has only been tested on the Ansible control node (127.0.0.1)
preflight_reports_host: "{{ reports_host }}"

# List of reports to generate
# src:  Is the report template file on the Ansible control node.
#       With no or relative path Ansible will look in the software role template directory.
#       Full path to find the template files elsewhere on the Ansible control node.
# dest: Is the destination file on the host (sw_reports_host.)
#       With no or relative path when the destination is the Ansible control node.
#       (sw_reports_host = 127.0.0.1) relative to the playbook directory.
#       Full path for other locations or on other hosts.
#       In either case the directory must already exist.
preflight_reports:
  - src:  preflight_report.csv.j2
    dest: preflight_report.csv
  - src:  preflight_report.html.j2
    dest: preflight_report.html
