---

# Set failed
- set_fact:
    cacheable: true
    sas_preflight:
      unreachable: false
      failed: true
      changed: "{{ result.changed | default(False) }}"
      msg: |
        preflight:
        {{ result.msg | default('Unexpected error') }}
    sas_common:
      unreachable: false
      failed: true
      changed: "{{ result.changed | default(False) }}"
      msg: |
        preflight:
        {{ result.msg | default('Unexpected error') }}
  when: preflight_reports_generate or preflight_facts_generate

# Propogate fail
- fail:
    msg: "{{ result.msg | default('Unexpected error') }}"
