---

# Set success
- set_fact:
    cacheable: true
    sas_preflight:  
      unreachable: false
      failed: false
      changed: "{{ result.changed | default(False) }}"
      msg: ''
    sas_common: 
      unreachable: false 
      failed: false
      changed: "{{ result.changed | default(False) }}"
      msg: '' 
  when: preflight_reports_generate or preflight_facts_generate
