---

# ------------------------------------------------------------------------------
# Debian - remove package 
# ------------------------------------------------------------------------------

# Remove package
- name: remove {{ package_key }}
  command:
    cmd: dpkg --purge {{ package_name }}
  register: pkg_remove 
