---

# ------------------------------------------------------------------------------
# HP-UX - upgrade package
# ------------------------------------------------------------------------------

- include_tasks: "install.yml"
