---

# Copy install package to host
- name: copy {{ package_key }} installer {{ package_file }} 
  copy:
    src: "{{ package_src }}"
    dest: "{{ package_dest }}"
  ignore_errors: true
  changed_when: false
