---

# Copy install package to host
- name: copy {{ package_key }} installer {{ package_file }}
  copy:
    src: "{{ package_src }}"
    dest: "{{ package_dest }}"
  ignore_errors: true
  changed_when: false
  register: rval

- fail:
    msg: "{{ rval.msg }}"
  when: rval.msg is defined and rval.msg
