---

# Set failed
- set_fact:
    cacheable: true
    sas_software:
      unreachable: false
      failed: true
      changed: "{{ result.changed | default(False) }}"
      msg: |
        software:
        {{ result.msg | default('Unexpected error') }}
    sas_common:
      unreachable: false
      failed: true
      changed: "{{ result.changed | default(False) }}"
      msg: |
        software:
        {{ result.msg | default('Unexpected error') }} 
  when: software_reports_generate or software_facts_generate

# Propogate fail
- fail:
    msg: "{{ result.msg | default('Unexpected error') }}"
