---

# Parse version from version response, if no version this will set it to an empty string
- set_fact: |
    sas_software_{{ package_key | replace('qpm-', '') }}_vers_{{ flag }}={{ pkg_version.stdout
    | default("", true)
    | regex_search("(?=.*)[\d]+\.[\d]+\.[\d]+[\.-][\d]+")
    | default("", true)
    | replace("-", ".") }}
    | cacheable=true
