---

galaxy_info:

  author: Mark Stillings <mark.stillings@oneidentity.com>

  company: One Identity

  description: >
    Manages the deployment of Privilege Manager software. The role supports software install, upgrade, downgrade, uninstall, and version checking.

  issue_tracker_url: https://github.com/OneIdentity/ansible-privilege-manager/issues

  license: Apache-2.0

  min_ansible_version: 2.9

  #
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
  - name: Amazon
    versions:
    - all
  - name: MacOSX
    versions:
    - 10.12
    - 10.13
    - 10.14
    - 10.15
  - name: EL
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: Fedora 
    versions:
    - all
  - name: FreeBSD
    versions:
    - all
  - name: AIX
    versions:
    - 7.1
    - 7.2
  - name: opensuse
    versions:
    - all
  - name: Solaris
    versions:
    - all
  - name: SLES
    versions:
    - 11
    - 12
    - 15
  - name: Ubuntu
    versions:
    - all

  # galaxy_tags: []

dependencies:
  - role: common
