---

# ------------------------------------------------------------------------------
# Redhat - install package
# ------------------------------------------------------------------------------

# Package install, copy installer
- include_tasks: utils/package_copy.yml

# Package install
- name: install {{ package_key }}
  command:
    cmd: rpm -ivh --nodeps {{ package_dest }}
  register: pkg_install
