---

# Join settings
# ------------------------------------------------------------------------------

# Valid options are: 'joined' or 'unjoined'
join_state: joined
join_password:
join_extra_args:


# Facts settings
# ------------------------------------------------------------------------------

join_facts_generate: "{{ facts_generate }}"
join_facts_verbose: "{{ facts_verbose }}"


# Report settings
# ------------------------------------------------------------------------------

join_reports_generate: "{{ reports_generate }}"
join_reports_backup: "{{ reports_backup }}"

# Format of details section in both HTML and CSV reports
# Valid options are: 'yaml' or 'json'
join_reports_details_format: "{{ reports_details_format }}"

# On which host should the reports be generated.
# TODO: This has only been tested on the Ansible control node (127.0.0.1)
join_reports_host: "{{ reports_host }}"

# List of reports to generate
# src:  Is the report template file on the Ansible control node.
#       With no or relative path Ansible will look in the client_sw role template directory.
#       Full path to find the template files elsewhere on the Ansible control node.
# dest: Is the destination file on the host (reports_host.)
#       With no or relative path when the destination is the Ansible control node.
#       (reports_host = 127.0.0.1) relative to the playbook directory.
#       Full path for other locations or on other hosts.
#       In either case the directory must already exist.
join_reports:
  - src:  join_report.csv.j2
    dest: join_report.csv
  - src:  join_report.html.j2
    dest: join_report.html
