---

# ------------------------------------------------------------------------------
# AIX - install package
# ------------------------------------------------------------------------------

# Package install, copy installer
- include_tasks: utils/package_copy.yml

# Package install
- name: install {{ package_key }}
  command:
    cmd: installp -acXd {{ package_dest }} all
  register: pkg_install 
  ignore_errors: true
  changed_when: true 
  failed_when: pkg_install.stdout | lower is search("failed")
