---

# ------------------------------------------------------------------------------
# AIX - grab package version
# ------------------------------------------------------------------------------

# Grab installed version of package
- name: get {{ package_key }} version
  shell:
    cmd: lslpp -cL | grep {{ package_name }}
  register: pkg_version
  changed_when: false
  failed_when: false
  ignore_errors: true
